### ISSUE TITLE
用最新版本,还是不行

### ISSUE THREAD

**Issue by nickeyfff** [isayme/smzdm#3]
报错哦.

{u'data': {u'slogan': u''}, u'error_code': 99, u'error_msg': [u'\u7b7e\u5230\u5f02\u5e38\uff0c\u8bf7\u91cd\u8bd5\uff08code\uff1a1\uff09'], u'func': u''}

翻过来就是: 签到异常，请重试

**Comment by isayme** [comment]
@nickeyfff 值得买的登录方式变了, 已经跟进修正了.
