### ISSUE TITLE
提示数据错误

### ISSUE THREAD

**Issue by zanderzhng** [isayme/smzdm#5]
前几天更新后就提示这个。

**Comment by YunEr-Wang** [comment]
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:838: I
nsecureRequestWarning: Unverified HTTPS request is being made. Adding certificat
e verification is strongly advised. See: https://urllib3.readthedocs.io/en/lates
t/security.html
  InsecureRequestWarning)
('success', {u'error_code': 1, u'error_msg': {u'public': u'\u6570\u636e\u9519\u8
bef'}})

**Comment by isayme** [comment]
还以为只有我自己在用这个呢~~~

**Comment by chauyuen** [comment]
哈哈哈哈，才不是呢。不过似乎持续有一段时间了，应该不是更新的问题。可能需要看看官网是不是改变了签到方式。

**Comment by YunEr-Wang** [comment]
搞搞搞

**Comment by isayme** [comment]
@zanderzhng @chauyuen @sykiewang 你们现在用的python都是什么版本? 我准备加个测试. 如果你们都是3的话, 我就不准备考虑对2的兼容了.

**Comment by YunEr-Wang** [comment]
表示之前为了用你的脚本，特地装的2.7，搞3吧

**Comment by chauyuen** [comment]
都可以接受，这个没影响。

**Comment by isayme** [comment]
恩, 那我尽量兼容吧 🐶

**Comment by YunEr-Wang** [comment]
不用了，直接搞3，不要弄2.x了

**Comment by YunEr-Wang** [comment]
弄好了吗？

**Comment by semihawk** [comment]
我也在用，签到报错
{"error_code":1,"error_msg":{"public":"数据错误"}}
希望能解决，谢谢

**Comment by isayme** [comment]
解决了. 值得买增强的请求的校验.
