### ISSUE TITLE
https错误

### ISSUE THREAD

**Issue by knva** [isayme/smzdm#7]
提示https错误,无法登陆

**Comment by mafeifan** [comment]
24行 BASE_URL 改为 'https://zhiyou.smzdm.com'
45行起 verify 都改为 True
r = self.session.get(self.BASE_URL, headers=headers, verify=True)
r = self.session.post(self.LOGIN_URL, data=params, headers=headers, verify=True)
r = self.session.get(self.CHECKIN_URL, headers=headers, verify=True)

**Comment by knva** [comment]
thankyou close
